FROM centos/python-38-centos7
USER root

# Variáveis de ambiente
ENV GUNICORN_WORKERS=2 \
    GUNICORN_TIMEOUT=300 \
    VERSAO=1.0.1

# Cria estrutura de diretórios
RUN mkdir -p /code/service

WORKDIR /code

# Copia APENAS os arquivos necessários
COPY core-swagger-api/setup.py .
COPY core-swagger-api/arvore_model2.pkl .
COPY core-swagger-api/service ./service

# Instala dependências
RUN pip install --no-cache-dir --upgrade pip==20.2.3 setuptools==50.3.0 && \
    pip3 install pandas gunicorn && \
    pip3 install -e .[dev]

CMD ["gunicorn", "--config", "/code/service/config/config.py", "service.service:app"]
